# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- upstream-deriv

pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: 'msizanoen/qtmbuilder-upstream-deriv'

steps:
  - task: Docker@2
    displayName: Build builder image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
  - task: Docker@2
    displayName: Publish image
    inputs:
      containerRegistry: DockerConn
      repository: $(imageName)
      command: push
