# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- hydra

pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: 'msizanoen/armv7-linux-rs'

steps:
  - script: |
      git clone --depth=1 -b fix-armv7-segfault https://github.com/msizanoen1/rust.git
    displayName: Get code
  - task: Docker@2
    displayName: Build builder image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: rust/src/ci/docker/dist-armv7-linux/Dockerfile
      buildContext: rust/src/ci/docker
  - task: Docker@2
    displayName: Publish image
    inputs:
      containerRegistry: DockerConn
      repository: $(imageName)
      command: push
